"""Document generation — Word (.docx) and PowerPoint (.pptx)."""

import io
import json
import os
from pathlib import Path

from src.config import get_settings


def _outputs_dir() -> Path:
    settings = get_settings()
    path = Path(getattr(settings, "uploads_dir", "uploads")) / "_generated"
    path.mkdir(parents=True, exist_ok=True)
    return path


async def create_docx(
    title: str,
    content: str,
    filename: str = "document.docx",
    session=None,
    workspace_id: str = "default",
) -> str:
    """Generate a professional Word document from markdown content."""
    try:
        from docx import Document
        from docx.shared import Inches, Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError:
        return json.dumps({"error": "python-docx not installed. Run: pip install python-docx"})

    doc = Document()

    # ── Style defaults ──────────────────────────────────────
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Calibri"
    font.size = Pt(11)
    font.color.rgb = RGBColor(0x1a, 0x1a, 0x1a)

    # ── Title ───────────────────────────────────────────────
    title_para = doc.add_heading(title, level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.LEFT
    for run in title_para.runs:
        run.font.size = Pt(24)
        run.font.color.rgb = RGBColor(0x1e, 0x40, 0xaf)

    # ── Parse markdown-like sections ────────────────────────
    sections = content.split("\n")
    for line in sections:
        stripped = line.strip()
        if not stripped:
            continue

        # Heading levels
        if stripped.startswith("## "):
            h = doc.add_heading(stripped[3:], level=1)
            for run in h.runs:
                run.font.color.rgb = RGBColor(0x1e, 0x40, 0xaf)
        elif stripped.startswith("### "):
            h = doc.add_heading(stripped[4:], level=2)
            for run in h.runs:
                run.font.color.rgb = RGBColor(0x33, 0x33, 0x33)
        elif stripped.startswith("- ") or stripped.startswith("* "):
            doc.add_paragraph(stripped[2:], style="List Bullet")
        elif stripped.startswith("1. "):
            doc.add_paragraph(stripped[3:], style="List Number")
        elif stripped == "---":
            doc.add_paragraph("_" * 50)
        else:
            para = doc.add_paragraph(stripped)
            para.space_after = Pt(6)

    # ── Footer ──────────────────────────────────────────────
    footer = doc.sections[0].footer
    footer.paragraphs[0].text = "Generated by AutoSteer"
    footer.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER

    # ── Save ────────────────────────────────────────────────
    safe_name = Path(filename).name.replace("..", "").replace("/", "_")
    if not safe_name.endswith(".docx"):
        safe_name = safe_name.rsplit(".", 1)[0] + ".docx" if "." in safe_name else safe_name + ".docx"
    out_path = _outputs_dir() / safe_name
    doc.save(str(out_path))

    return json.dumps({
        "ok": True,
        "filename": safe_name,
        "path": str(out_path),
        "size_bytes": out_path.stat().st_size,
        "format": "docx",
    }, indent=2)


async def create_pptx(
    title: str,
    slides: str,
    filename: str = "presentation.pptx",
    session=None,
    workspace_id: str = "default",
) -> str:
    """Generate a professional PowerPoint presentation.

    Args:
        title: Presentation title (slide 1 heading)
        slides: Slide content — one slide per line, format: "Slide Title | bullet1; bullet2; bullet3"
    """
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
        from pptx.dml.color import RGBColor
        from pptx.enum.text import PP_ALIGN
    except ImportError:
        return json.dumps({"error": "python-pptx not installed. Run: pip install python-pptx"})

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    # ── Title slide ─────────────────────────────────────────
    slide_layout = prs.slide_layouts[6]  # blank
    slide = prs.slides.add_slide(slide_layout)

    # Background
    bg = slide.background
    fill = bg.fill
    fill.solid()
    fill.fore_color.rgb = RGBColor(0x1e, 0x40, 0xaf)

    # Title text
    left = Inches(1)
    top = Inches(2.5)
    width = Inches(11.333)
    height = Inches(2)
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = title
    p.font.size = Pt(40)
    p.font.bold = True
    p.font.color.rgb = RGBColor(0xff, 0xff, 0xff)
    p.alignment = PP_ALIGN.LEFT

    # ── Content slides ──────────────────────────────────────
    slide_lines = [s.strip() for s in slides.split("\n") if s.strip()]
    for slide_line in slide_lines:
        parts = slide_line.split("|", 1)
        slide_title = parts[0].strip()
        bullets_str = parts[1].strip() if len(parts) > 1 else ""
        bullets = [b.strip() for b in bullets_str.split(";") if b.strip()]

        slide = prs.slides.add_slide(slide_layout)
        bg = slide.background
        fill = bg.fill
        fill.solid()
        fill.fore_color.rgb = RGBColor(0xff, 0xff, 0xff)

        # Slide title
        left = Inches(0.8)
        top = Inches(0.4)
        width = Inches(11.733)
        height = Inches(1)
        txBox = slide.shapes.add_textbox(left, top, width, height)
        tf = txBox.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.text = slide_title
        p.font.size = Pt(28)
        p.font.bold = True
        p.font.color.rgb = RGBColor(0x1e, 0x40, 0xaf)

        # Accent line
        line = slide.shapes.add_shape(
            1,  # MSO_SHAPE.RECTANGLE
            Inches(0.8), Inches(1.3), Inches(2), Inches(0.04)
        )
        line.fill.solid()
        line.fill.fore_color.rgb = RGBColor(0x3b, 0x82, 0xf6)
        line.line.fill.background()

        # Bullets
        left = Inches(0.8)
        top = Inches(1.7)
        width = Inches(11.733)
        height = Inches(5)
        txBox = slide.shapes.add_textbox(left, top, width, height)
        tf = txBox.text_frame
        tf.word_wrap = True
        for i, bullet in enumerate(bullets):
            if i == 0:
                p = tf.paragraphs[0]
            else:
                p = tf.add_paragraph()
            p.text = f"  {bullet}"
            p.font.size = Pt(18)
            p.font.color.rgb = RGBColor(0x33, 0x33, 0x33)
            p.space_after = Pt(12)
            p.level = 0

    # ── Save ────────────────────────────────────────────────
    safe_name = Path(filename).name.replace("..", "").replace("/", "_")
    if not safe_name.endswith(".pptx"):
        safe_name = safe_name.rsplit(".", 1)[0] + ".pptx" if "." in safe_name else safe_name + ".pptx"
    out_path = _outputs_dir() / safe_name
    prs.save(str(out_path))

    return json.dumps({
        "ok": True,
        "filename": safe_name,
        "path": str(out_path),
        "slides": len(prs.slides),
        "size_bytes": out_path.stat().st_size,
        "format": "pptx",
    }, indent=2)
