"""Integration provider definitions for the hub UI."""

PROVIDERS = [
    {
        "id": "tavily",
        "name": "Tavily Search",
        "description": "Web search for all agents (global API key)",
        "scopes": ["web_search"],
        "connect_type": "api_key",
        "env_var": "TAVILY_API_KEY",
    },
    {
        "id": "slack",
        "name": "Slack",
        "description": "Post and read Slack messages",
        "scopes": ["channels:read", "chat:write"],
        "connect_type": "bot_token",
        "env_var": "SLACK_BOT_TOKEN",
    },
    {
        "id": "github",
        "name": "GitHub",
        "description": "Read repos, issues, PRs; create issues",
        "scopes": ["repo", "read:org"],
        "connect_type": "pat",
        "env_var": "GITHUB_TOKEN",
    },
    {
        "id": "notion",
        "name": "Notion",
        "description": "Export documents to Notion pages",
        "scopes": ["pages:write"],
        "connect_type": "integration_token",
        "env_var": "NOTION_TOKEN",
    },
    {
        "id": "linear",
        "name": "Linear",
        "description": "Read and create Linear issues",
        "scopes": ["read", "write"],
        "connect_type": "api_key",
        "env_var": "LINEAR_API_KEY",
    },
    {
        "id": "google",
        "name": "Google Workspace",
        "description": "Google Docs, Sheets, GA4 (service account)",
        "scopes": ["documents", "spreadsheets", "analytics"],
        "connect_type": "service_account",
        "env_var": "GOOGLE_SERVICE_ACCOUNT_JSON",
    },
    # Phase C
    {
        "id": "hubspot",
        "name": "HubSpot",
        "description": "Read CRM contacts/deals; add deal notes",
        "scopes": ["crm.objects.contacts.read", "crm.objects.deals.read"],
        "connect_type": "oauth_token",
        "env_var": "HUBSPOT_ACCESS_TOKEN",
    },
    {
        "id": "apollo",
        "name": "Apollo.io",
        "description": "Company and contact prospecting search",
        "scopes": ["search"],
        "connect_type": "api_key",
        "env_var": "APOLLO_API_KEY",
    },
    {
        "id": "posthog",
        "name": "PostHog",
        "description": "Product analytics events and insights",
        "scopes": ["events:read"],
        "connect_type": "api_key",
        "env_var": "POSTHOG_API_KEY",
    },
    {
        "id": "stripe",
        "name": "Stripe",
        "description": "Read-only subscription and MRR metrics",
        "scopes": ["read_only"],
        "connect_type": "restricted_key",
        "env_var": "STRIPE_SECRET_KEY",
    },
    {
        "id": "intercom",
        "name": "Intercom",
        "description": "Read support conversations",
        "scopes": ["conversations:read"],
        "connect_type": "access_token",
        "env_var": "INTERCOM_ACCESS_TOKEN",
    },
    {
        "id": "zendesk",
        "name": "Zendesk",
        "description": "Read support tickets",
        "scopes": ["tickets:read"],
        "connect_type": "api_token",
        "env_var": "ZENDESK_API_TOKEN",
    },
    {
        "id": "sentry",
        "name": "Sentry",
        "description": "Read error issues",
        "scopes": ["project:read"],
        "connect_type": "auth_token",
        "env_var": "SENTRY_AUTH_TOKEN",
    },
    {
        "id": "typeform",
        "name": "Typeform",
        "description": "Create surveys from agent specs",
        "scopes": ["forms:write"],
        "connect_type": "access_token",
        "env_var": "TYPEFORM_ACCESS_TOKEN",
    },
    {
        "id": "resend",
        "name": "Resend",
        "description": "Send emails (beta, requires approval)",
        "scopes": ["emails:send"],
        "connect_type": "api_key",
        "env_var": "RESEND_API_KEY",
    },
    {
        "id": "postmark",
        "name": "Postmark",
        "description": "Send transactional emails (beta, requires approval)",
        "scopes": ["emails:send"],
        "connect_type": "server_token",
        "env_var": "POSTMARK_API_KEY",
    },
    # Phase D
    {
        "id": "e2b",
        "name": "E2B",
        "description": "Cloud code sandbox (optional)",
        "scopes": ["sandbox:run"],
        "connect_type": "api_key",
        "env_var": "E2B_API_KEY",
    },
    {
        "id": "wandb",
        "name": "Weights & Biases",
        "description": "Read ML experiment runs",
        "scopes": ["runs:read"],
        "connect_type": "api_key",
        "env_var": "WANDB_API_KEY",
    },
    # Phase E
    {
        "id": "zapier",
        "name": "Zapier / Make",
        "description": "Fire automation webhooks",
        "scopes": ["webhook"],
        "connect_type": "webhook_url",
        "env_var": "ZAPIER_WEBHOOK_URL",
    },
    {
        "id": "docusign",
        "name": "DocuSign",
        "description": "Generate envelope drafts",
        "scopes": ["envelope:write"],
        "connect_type": "oauth_token",
        "env_var": "DOCUSIGN_ACCESS_TOKEN",
    },
    {
        "id": "figma",
        "name": "Figma",
        "description": "Read file metadata",
        "scopes": ["file:read"],
        "connect_type": "pat",
        "env_var": "FIGMA_ACCESS_TOKEN",
    },
    {
        "id": "pagespeed",
        "name": "Google PageSpeed",
        "description": "Lighthouse / PageSpeed performance audits",
        "scopes": ["audit"],
        "connect_type": "api_key",
        "env_var": "GOOGLE_PAGESPEED_API_KEY",
    },
]

# provider id → module exposing async test_connection(session, workspace_id) -> dict
TEST_HANDLERS = {
    "slack": "src.integrations.slack",
    "github": "src.integrations.github",
    "notion": "src.integrations.notion",
    "linear": "src.integrations.linear",
    "google": "src.integrations.google",
    "hubspot": "src.integrations.hubspot",
    "apollo": "src.integrations.apollo",
    "posthog": "src.integrations.posthog",
    "stripe": "src.integrations.stripe_metrics",
    "typeform": "src.integrations.typeform",
    "intercom": "src.integrations.intercom",
    "zendesk": "src.integrations.zendesk",
    "sentry": "src.integrations.sentry",
    "resend": "src.integrations.email",
    "postmark": "src.integrations.email",
    "e2b": "src.integrations.sandbox",
    "wandb": "src.integrations.wandb",
    "zapier": "src.integrations.zapier",
    "docusign": "src.integrations.docusign",
    "figma": "src.integrations.figma",
    "pagespeed": "src.integrations.lighthouse",
}
