"""initial

Revision ID: 0982e84e9625
Revises:
Create Date: 2026-07-11 17:12:27.403161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

try:
    import pgvector as _pgv
except ImportError:
    _pgv = None


# revision identifiers, used by Alembic.
revision: str = '0982e84e9625'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('soul_config', sa.JSON(), nullable=False),
    sa.Column('agent_config', sa.JSON(), nullable=False),
    sa.Column('llm_model', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=64), nullable=False),
    sa.Column('step_id', sa.String(length=128), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_workflow_run_id'), 'approval_requests', ['workflow_run_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_workspace_id'), 'approval_requests', ['workspace_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_workspace_id'), 'conversations', ['workspace_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_workspace_id'), 'document_chunks', ['workspace_id'], unique=False)
    op.create_table('integration_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('encrypted_token', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'provider', name='uq_workspace_provider')
    )
    op.create_index(op.f('ix_integration_connections_provider'), 'integration_connections', ['provider'], unique=False)
    op.create_index(op.f('ix_integration_connections_workspace_id'), 'integration_connections', ['workspace_id'], unique=False)
    op.create_table('memory_embeddings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('embedding', _pgv.sqlalchemy.vector.VECTOR(dim=1536) if _pgv else sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_embeddings_conversation_id'), 'memory_embeddings', ['conversation_id'], unique=False)
    op.create_table('memory_facts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('fact_type', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_facts_conversation_id'), 'memory_facts', ['conversation_id'], unique=False)
    op.create_table('shared_state',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('workspace_id', 'key')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('from_agent', sa.String(length=255), nullable=False),
    sa.Column('to_agent', sa.String(length=255), nullable=False),
    sa.Column('message_type', sa.Enum('REQUEST', 'RESPONSE', 'ESCALATION', 'NOTIFICATION', 'HANDOFF', name='messagetype'), nullable=False),
    sa.Column('priority', sa.Enum('P0', 'P1', 'P2', 'P3', 'P4', name='priority'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_workspace_id'), 'messages', ['workspace_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'ESCALATED', name='taskstatus'), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('outputs', sa.JSON(), nullable=True),
    sa.Column('sla_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_workspace_id'), 'tasks', ['workspace_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('workflow_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='workflowstatus'), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cron_expression', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_workspace_id'), 'workflows', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflows_workspace_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_tasks_workspace_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_messages_workspace_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('shared_state')
    op.drop_index(op.f('ix_memory_facts_conversation_id'), table_name='memory_facts')
    op.drop_table('memory_facts')
    op.drop_index(op.f('ix_memory_embeddings_conversation_id'), table_name='memory_embeddings')
    op.drop_table('memory_embeddings')
    op.drop_index(op.f('ix_integration_connections_workspace_id'), table_name='integration_connections')
    op.drop_index(op.f('ix_integration_connections_provider'), table_name='integration_connections')
    op.drop_table('integration_connections')
    op.drop_index(op.f('ix_document_chunks_workspace_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_conversations_workspace_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_approval_requests_workspace_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_workflow_run_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_table('agents')
    # ### end Alembic commands ###
